version: "3.9"

services:
  clonebot:
    image: ghcr.io/missemily2022/clonebot:new
    container_name: clonebot
    environment:
      - telegram_token=${5541861255:AAEgxyJ2ZiBqMkDeKfR2-8-slQEapK2hlgk}
      - user_ids=${920303927}
      - group_ids=${-1}
      - PORT=${8080}
    ports:
      - ${8080}:${8080}
    restart: unless-stopped
